version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dmathieu/bobette
    steps:
      - checkout
      - run: make install
      - run: make test
